FROM dockerfile/ubuntu

RUN \
  apt-get update && \
  apt-get install -y python python-dev python-pip python-virtualenv make && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /data

ADD /src /data

RUN make 
